### ISSUE TITLE
Allmän städning

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#115]
Vi borde städa upp en del i cashflow, uppdatera en del gems, bli av med en massa deprecation-varningar i testkörningarna, samt fixa så att alla tester faktiskt går igenom.

Detta är en ganska lång lista, så jag väntar mig inte att få en lösning i en klump, men jag tänker att det kanske kan vara bra att samla ihop en massa saker som behöver göras i en lista.
- [x] fixa cucumber-testerna
- [x] byt ut bootstrap.js mot ett gem (WIP @Koronen)
- [x] flytta funktionaliteten från purchase_observer och debt_observer någon annanstans (#125)
  - [x] kasta ut no_peeping_toms (gem för att hantera observers i tester, som dessutom är deprecated)
- [ ] bli av med alla varningar i testkörningarna
  - [x] uppgradera RedCloth
  - [x] undersök varför `features/support/env.rb` laddas två gånger (#127)
  - [ ] undersök varför rspec-testerna körs två gånger på travis
- [x] migrera till postgresql (#129)
  - [x] byt ut solr mot postgres inbyggda full-text-sökning (#129)
- [x] uppgradera till ruby 2.1
- [ ] uppgradera till ruby 2.2?
- [x] uppgradera till rspec 3 (#140)
- [ ] uppgradera till rails 4
  - [ ] byt ut i18n_routing mot något annat, eftersom den inte funkar med rails 4
- [ ] snabba upp testerna

**Comment by Frost** [comment]
Cucumber-testerna är fixade i #119. Den tar även bort en del varningar.

**Comment by Frost** [comment]
Det var tydligen en noop att köra cashflow på ruby 2.1. Jag lade till den i travis-configen, och [den körde fint rätt ur lådan](https://travis-ci.org/datasektionen/cashflow/jobs/44803127). :)
